### ISSUE TITLE
I can't Extract Files. [Errno 2] No such file or directory: 'deps/CydiaSubstrate.zip

### ISSUE THREAD

**Issue by qnblackcat** [CrafterPika/ppsideloader_py#2]
I can't Extract Files in the first time. Got this error from Terminal 
`Creating Directories!

Done!

Extracting Importand Files!

Exception in Tkinter callback
Traceback (most recent call last):

  File "tkinter/__init__.py", line 1883, in __call__

  File "ppsideloader_py.py", line 56, in extract

  File "zipfile.py", line 1251, in __init__

FileNotFoundError: [Errno 2] No such file or directory: 'deps/CydiaSubstrate.zip`

It confuses me because I can see CydiaSubstrate.zip in "deps"
![Screen Shot 2020-09-21 at 21 19 40](https://user-images.githubusercontent.com/52943116/93779829-932d6e00-fc51-11ea-9f53-8391af17ef1f.png)

**Comment by CrafterPika** [comment]
did you tried to cd into the folder directory of the executable?

**Comment by CrafterPika** [comment]
closing issue due to inactivity
